[package]
name = "example-tokio-tracing-wasm"
version = "0.0.0"
authors = ["The Wasmtime Project Developers"]
edition = "2018"
publish = false

[[bin]]
path = "tokio-wasi.rs"
name = "tokio-tracing-wasi"
